"""Add token_scores table for historical scoring

Revision ID: 1683566ccf30
Revises: b6d321ba365a
Create Date: 2026-01-13 19:10:07.338938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1683566ccf30'
down_revision: Union[str, None] = 'b6d321ba365a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.Column('calculated_score', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('snapshot_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('price_change_percent', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_token_scores_calculated_at', 'token_scores', ['calculated_at'], unique=False)
    op.create_index('idx_token_scores_token_time', 'token_scores', ['token_id', 'calculated_at'], unique=False)
    op.create_index('idx_token_scores_tournament_time', 'token_scores', ['tournament_id', 'token_id', 'calculated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_token_scores_tournament_time', table_name='token_scores')
    op.drop_index('idx_token_scores_token_time', table_name='token_scores')
    op.drop_index('idx_token_scores_calculated_at', table_name='token_scores')
    op.drop_table('token_scores')
    # ### end Alembic commands ###
