"""add_prize_distribution_fields

Revision ID: 9ecc8d83fcc0
Revises: e6ddbd9eb0bb
Create Date: 2026-01-18 21:12:13.312321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ecc8d83fcc0'
down_revision: Union[str, None] = 'e6ddbd9eb0bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament_results', sa.Column('prizes', sa.JSON(), nullable=True))
    op.add_column('tournaments', sa.Column('reward_types', sa.JSON(), nullable=True))
    op.add_column('tournaments', sa.Column('prize_pools', sa.JSON(), nullable=True))
    op.drop_column('tournaments', 'prize_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('prize_amount', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=True))
    op.drop_column('tournaments', 'prize_pools')
    op.drop_column('tournaments', 'reward_types')
    op.drop_column('tournament_results', 'prizes')
    # ### end Alembic commands ###
