"""add_alpha_test_access_table

Revision ID: c386c065fd27
Revises: 5559a247c5a8
Create Date: 2026-01-23 10:46:32.440647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c386c065fd27'
down_revision: Union[str, None] = '5559a247c5a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alpha_test_access',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('wallet_address', sa.String(length=42), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wallet_address')
    )
    # Remove these 2 lines:
    # op.drop_index('idx_job_locks_expires', table_name='job_locks')
    # op.drop_table('job_locks')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove entire job_locks creation block (already in older migration)
    op.drop_table('alpha_test_access')
    # ### end Alembic commands ###
