"""Add weight to token score

Revision ID: d55db82da219
Revises: 7038e0042b9c
Create Date: 2026-02-07 20:38:09.831496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd55db82da219'
down_revision: Union[str, None] = '7038e0042b9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token_scores', sa.Column('weight', sa.Integer(), nullable=True))
    op.drop_index('idx_users_referred_by', table_name='users')
    op.drop_constraint('fk_users_referred_by', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'users', ['referred_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('fk_users_referred_by', 'users', 'users', ['referred_by_id'], ['id'], ondelete='SET NULL')
    op.create_index('idx_users_referred_by', 'users', ['referred_by_id'], unique=False)
    op.drop_column('token_scores', 'weight')
    # ### end Alembic commands ###
